export const START_LOADING = 'START_LOADING';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const UPDATE_SIGN_IN_FACEBOOK = 'UPDATE_SIGN_IN_FACEBOOK';
export const UPDATE_SIGN_IN_GOOGLE = 'UPDATE_SIGN_IN_GOOGLE';